/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory_system.GUI;

import com.mycompany.inventory_system.Functionalities.*;
import com.mycompany.inventory_system.Tools.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;


/**
 *
 * @author admin
 */
public class AddEditItem extends javax.swing.JFrame {
    public static boolean edit = false; 
    public static String edit_item_name = null;
    public static ProductDashboard product_dashboard;
    
    
    public boolean warning_change_name = false;
    /**
     * Creates new form AddEditItem
     */
    public AddEditItem() {
        initComponents();
   java.net.URL imageUrl = getClass().getResource("/com/mycompany/inventory_system_images/Logo.png");
            Image icon = Toolkit.getDefaultToolkit().getImage(imageUrl);
            this.setIconImage(icon);
            
        if(edit) {
         item_name1.setText(edit_item_name);
         item_quantity.setText(String.valueOf(AccountHandler.items.get(edit_item_name).quantity));
         manufacture_date.setText(AccountHandler.items.get(edit_item_name).manufacture_date);
         expiration_date.setText(AccountHandler.items.get(edit_item_name).expiration_date);
        } else {
         item_quantity.setText("0");
         manufacture_date.setText("mm/dd/yy");
         expiration_date.setText("mm/dd/yy");
        }
        warning_change_name = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new RoundedButton("LOGIN",20);
        jPanel2 = new RoundedPanel(35);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manufacture_date = new javax.swing.JTextField();
        expiration_date = new javax.swing.JTextField();
        jButton2 = new RoundedButton("LOGIN",20);
        jButton3 = new RoundedButton("LOGIN",20);
        jButton1 = new RoundedButton("LOGIN",20);
        item_quantity = new javax.swing.JTextField();
        item_name1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InvenTra");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(80, 180, 120));
        jButton4.setForeground(new java.awt.Color(230, 230, 230));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 30));

        jPanel2.setBackground(new java.awt.Color(44, 47, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item Name :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manufacure Date :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expiration Date : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 73, -1, -1));

        manufacture_date.setBackground(new java.awt.Color(182, 176, 159));
        manufacture_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacture_dateActionPerformed(evt);
            }
        });
        jPanel2.add(manufacture_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        expiration_date.setBackground(new java.awt.Color(182, 176, 159));
        expiration_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiration_dateActionPerformed(evt);
            }
        });
        jPanel2.add(expiration_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, -1));

        jButton2.setBackground(new java.awt.Color(80, 180, 120));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 40, -1));

        jButton3.setBackground(new java.awt.Color(80, 180, 120));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, -1));

        jButton1.setBackground(new java.awt.Color(80, 180, 120));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        item_quantity.setBackground(new java.awt.Color(182, 176, 159));
        item_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_quantityActionPerformed(evt);
            }
        });
        jPanel2.add(item_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 40, -1));

        item_name1.setBackground(new java.awt.Color(182, 176, 159));
        item_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_name1ActionPerformed(evt);
            }
        });
        jPanel2.add(item_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 39, 175, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/inventory_system_images/Untitled design (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 2960, 2250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 103, 290, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/inventory_system_images/Untitled design.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, -220, 1180, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(edit) {
            
          if(!item_name1.getText().equals(edit_item_name) && !warning_change_name) {
               JOptionPane.showMessageDialog(null,"Are you sure you want to change name?");
              warning_change_name = true;
              return;
          }
         
        }
        
        if(warning_change_name) {
           LogRecorder.Record("  [rename item] - " + edit_item_name + " into " + item_name1.getText());
          AccountHandler.items.remove(edit_item_name);
        }
        
        Item item = new Item();
        item.name = item_name1.getText();
        if(item.name.equals("")) {
             JOptionPane.showMessageDialog(null,"Empty name. ");
            return;
        }
        try {
        item.quantity = Integer.parseInt(item_quantity.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Only Number is allowed ");
            item_quantity.setText("0");
            return;
        }
        
        //manufacture date and expiration date
        try {
        DateChecker.CheckDate(manufacture_date.getText());
         item.manufacture_date = manufacture_date.getText();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
            manufacture_date.setText("mm/dd/yy");
            return;
        }
        try {
        DateChecker.CheckDate(expiration_date.getText());
         item.expiration_date = expiration_date.getText();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
            expiration_date.setText("mm/dd/yy");
            return;
        }
        if(!edit) LogRecorder.Record("  [add item] - " + item_name1.getText());
      AccountHandler.items.put(item_name1.getText(), item);
      product_dashboard.UpdateAllItems();
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //minus
      int current_count;
        try {
            current_count = Integer.parseInt(item_quantity.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Only Number is allowed ");
            item_quantity.setText("0");
            return;
        }
        current_count--;
        item_quantity.setText(String.valueOf(current_count));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //add
        int current_count;
        try {
            current_count = Integer.parseInt(item_quantity.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Only Number is allowed ");
            item_quantity.setText("0");
            return;
        }
        current_count++;
        item_quantity.setText(String.valueOf(current_count));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void item_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_quantityActionPerformed

    private void item_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_name1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void manufacture_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacture_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacture_dateActionPerformed

    private void expiration_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiration_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiration_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField expiration_date;
    private javax.swing.JTextField item_name1;
    private javax.swing.JTextField item_quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField manufacture_date;
    // End of variables declaration//GEN-END:variables
}
