/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory_system.GUI;

import com.mycompany.inventory_system.Functionalities.*;
import com.mycompany.inventory_system.Tools.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class RemoveItem extends javax.swing.JFrame {
    public static ProductDashboard product_dashboard;
    /**
     * Creates new form RemoveItem
     */
    public RemoveItem() {
        initComponents();
   java.net.URL imageUrl = getClass().getResource("/com/mycompany/inventory_system_images/Logo.png");
            Image icon = Toolkit.getDefaultToolkit().getImage(imageUrl);
            this.setIconImage(icon);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new RoundedButton("LOGIN",20);
        jPanel2 = new RoundedPanel(35);
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new RoundedButton("LOGIN",20);
        item_name1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InvenTra");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(80, 180, 120));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, 40));

        jPanel2.setBackground(new java.awt.Color(44, 47, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item Name :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        jButton1.setBackground(new java.awt.Color(80, 180, 120));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        item_name1.setBackground(new java.awt.Color(182, 176, 159));
        item_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_name1ActionPerformed(evt);
            }
        });
        jPanel2.add(item_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 39, 175, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/inventory_system_images/Untitled design (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 2960, 2250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 153, 290, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/inventory_system_images/Untitled design.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -260, 1550, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        String username = userTextF.getText();
        String password = passwordTextF.getText();
        CheckUserlogin checkUserLogin = new CheckUserlogin();
        String result = checkUserLogin.checkUser(username,password);

        if (result.equals("correct")){
            ProductDashboard productD = new ProductDashboard();
            productD.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Wrong Username or Password");
        }
        */
      if(item_name1.getText().equals("")) {
           JOptionPane.showMessageDialog(null,"Empty Name.");
          this.dispose();
          return;
      }
      if(!AccountHandler.items.containsKey(item_name1.getText())) {
          JOptionPane.showMessageDialog(null,"Object does not exist.");
          this.dispose();
          return;
      }
      LogRecorder.Record("  [remove item] - " + item_name1.getText());
      AccountHandler.items.remove(item_name1.getText());
      product_dashboard.UpdateAllItems();
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void item_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_name1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField item_name1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
